export default function AboutUs() {
  return (
    <div className="mx-auto w-max max-w-6xl gap-12 px-4 py-20">
      <h1 className="mb-6 text-lg font-semibold">About Us </h1>

      <p className="mb-6">
        At BTE Analytics, we&apos;re on a mission to transform the landscape of athlete data ownership and empowerment.
        We&apos;re a team of former athletes who, like many others, trained, competed, and pushed ourselves to the
        limits—but we never saw financial returns from the data generated by our hard work. The opportunities for
        athletes today are different, but many still struggle to access and monetize their own performance data.
        That&apos;s why we created BTE Analytics: to build a future where athletes are at the center of their own
        data-driven success stories.
      </p>

      <p className="mb-6">
        Our goal is to create a thriving middle class for athletes by putting the power of data directly in their hands.
        We believe that athletes shouldn&apos;t just be consumers of their own performance data; they should profit from
        it. Through our platform, athletes can gamify their stats, giving fans exclusive insights into every highlight
        and key moment, while earning income that recognizes the value of their efforts.
      </p>

      <p className="mb-6">
        At the same time, we&apos;re providing athletes with advanced, detailed analytics that help them continuously
        improve their game. We&apos;ve been on both sides of the locker room: we know how much athletes invest in their
        training, and we understand the importance of having clear, actionable data to refine skills and optimize
        performance. That&apos;s why BTE Analytics prioritizes tools that help athletes not only engage with fans but
        also elevate their game.
      </p>

      <p className="mb-6">
        We&apos;re dedicated to a vision where every athlete has access to, control over, and benefits from the data
        they create. This is more than a platform; it&apos;s a movement that brings athletes, fans, and brands together
        in a way that ensures athletes can leverage their own data for financial gain and career growth. We&apos;re
        putting athlete data in the hands of athletes—and building a community that values and uplifts the hard work
        behind every stat.
      </p>
    </div>
  )
}
